version: '3'

services:
  messaging-api:
    container_name: 'messaging-api'
    build: ./messaging-api
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - database
    networks:
      - shared-net

  database:
    image: mongo
    container_name: database
    hostname: database
    restart: always
    ports:
      - 27030:27017
    networks:
      - shared-net
    command: mongod --bind_ip_all

networks:
  shared-net:
    driver: bridge